import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "First Next App",
  description: "Generated by M.jamshaid khan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
